### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by majkinetor** [Baggykiin/pass-winmenu#18]
Mentioned in #9.

Please take a look before publishing: https://github.com/majkinetor/au-packages/tree/pass-winmenu/pass-winmenu.

Most notably, the [chocolateyInstaller](https://github.com/majkinetor/au-packages/blob/pass-winmenu/pass-winmenu/tools/chocolateyInstall.ps1).

It will pull gpg [automatically](https://github.com/majkinetor/au-packages/blob/pass-winmenu/pass-winmenu/pass-winmenu.nuspec#L36) and keep updating it afterwards.

**Comment by Baggykiin** [comment]
Looks good, thanks for creating!

**Comment by majkinetor** [comment]
OK, its published now and it will automatically follow your latest Github releases.

**Comment by majkinetor** [comment]
https://chocolatey.org/packages/pass-winmenu/1.6
