### ISSUE TITLE
Under some conditions GPG may hang indefinitely

### ISSUE THREAD

**Issue by Baggykiin** [Baggykiin/pass-winmenu#20]
Some unknown operations can seemingly cause `gpg-agent.exe` to enter a state where it won't be able to process any requests from `gpg.exe`. When this happens, `gpg.exe` hangs indefinitely without producing any output.

Ideally the cause for this condition should be identified. It is possible that GPG will emit an error message when the agent enters the 'failure state'. Logging all output may help detect this.

If no cause can be identified, a workaround will be required. One way to work around this issue would be to kill GPG (and gpg-agent) if it does not produce any output at all after a set amount of time, and retry the attempted decryption/encryption operation.

**Comment by ferraith** [comment]
I can confirm that bug. It typically happens under high load of the CPU.

**Comment by Baggykiin** [comment]
Basic implementation in 7c493ad, needs more testing + maybe a config flag to disable the feature.
