### ISSUE TITLE
Forward SSH passphrase requests to the user

### ISSUE THREAD

**Issue by Baggykiin** [Baggykiin/pass-winmenu#24]
If you use an SSH key with a passphrase, it's not possible to use the context menu options in pass-winmenu to synchronise your password repository. Because pass-winmenu launches Git without a shell, Git has no way to request your SSH passphrase, causing it to ignore any passphrase-protected keys, which means it won't be able to connect to the remote repository.

This will probably involve starting an SSH agent and requesting it to load an SSH key, as well as providing it with a passphrase.

**Comment by Baggykiin** [comment]
https://git-scm.com/docs/gitcredentials

**Comment by hafstrom** [comment]
I've used both versions in my commit (and message) above in conjunction with native-git. I haven't done much experimenting with builtin so far.

**Comment by Baggykiin** [comment]
Thanks for the PR. I'll test it to see see how it works, but it seems like a good idea to support `GIT_SSH` regardless.

**Comment by Baggykiin** [comment]
Implemented in the pre-release.
