### ISSUE TITLE
Automatically check for and install updates

### ISSUE THREAD

**Issue by Nauxuron** [Baggykiin/pass-winmenu#26]
I would like to see a message if an update for pass-winmenu is available, with the option to install the update. This relies on #25 to be implemented first.

**Comment by majkinetor** [comment]
You can have that with chocolatey package today.

**Comment by Baggykiin** [comment]
I would like to add this for users who do not use the Chocolatey package, but obviously the Chocolatey version should not have this enabled.

It should be possible to disable this feature for those who don't want to use it.

@majkinetor What do you think? Should people using the Chocolatey version still get a message informing them that a new version is available (but requiring them to use Chocolatey to update instead), or should they not be notified of new versions at all?

**Comment by majkinetor** [comment]
I let that to users but add parameter for them to choose. We can do that here too.
