### ISSUE TITLE
Allow to configure keys to select password

### ISSUE THREAD

**Issue by rmolin88** [Baggykiin/pass-winmenu#28]
For example I start typing but the password I need is a choice that is not immediate. It would be great to allow for `Tab` for example to select the key I want. Like, instead of having to press the `Down/Up` keys, I could use `Tab/Shift+Tab`, or the sort `Ctrl+j/Ctrl+k`, etc..

Great software, thanks!

**Comment by Baggykiin** [comment]
Good idea, I think shortcuts for `Tab/Shift+Tab` would be sensible to have by default.
Different shortcuts could then be set in the configuration file.
