### ISSUE TITLE
How to build binaries

### ISSUE THREAD

**Issue by 0xphk** [Baggykiin/pass-winmenu#33]
Hi, 

not sure if this is an issue or I am missing something, but regarding to the description, there should be a binary file in the downloaded .zip file. But it's missing the bin or the instructions how to build it. 

I checked the build.ps1 file but it looks like it just tries to copy some file from not existent ./bin folder. 

`line 35: cp "bin/Release/pass-winmenu.exe" "$PKGDIR/pass-winmenu.exe"`

Any hint how to get this running is appreciated.

**Comment by Baggykiin** [comment]
Are you trying to install the program or do you want to set up your own development environment?

If you just want to install it, you can grab the release from [here](https://github.com/Baggykiin/pass-winmenu/releases), the zip file contains the `pass-winmenu.exe` binary.

**Comment by 0xphk** [comment]
Thanks, I missed the release page and fiddled with the source files ;)
