### ISSUE TITLE
Doesn't seem to support UNIX style newlines

### ISSUE THREAD

**Issue by Gigahawk** [Baggykiin/pass-winmenu#35]
Passwords generated using gopass on Linux don't work properly when synced over. pass-winmenu will just put an empty string into the clipboard.

If I edit the password file using pass-winmenu the password correctly shows up, and saving it will allow pass-winmenu to read it properly.

This gets really annoying since I have to generate the password on one computer, push, then pull on my Windows computer and push again to make it readable to all of my pass clients.

**Comment by willpower232** [comment]
All of my passwords were generated in Debian or Ubuntu on Windows using the original `pass` command. Vim tells me that the newlines in the file are UNIX and I've not encountered this in pass-winmenu.

I saved the output of `gpg -d one_of_my_passwords.gpg` to a file and opened it in vim with these settings https://stackoverflow.com/a/44543376. I only saw `¶`. Could you verify what line endings are in the files this way?

**Comment by Baggykiin** [comment]
I think it's a slightly different bug. Both CRLF and LF line endings are supported, but it looks like the password isn't extracted properly if the password file does not have any line endings at all.
