### ISSUE TITLE
On Quit, process isn't terminated

### ISSUE THREAD

**Issue by alexzeitgeist** [Baggykiin/pass-winmenu#38]
When you right-click on "Quit", you'll notice that the pass-winmenu.exe process still lingers in memory. It seems that the menu item doesn't trigger the necessary exit calls (e.g. Application.Exit(), Environment.Exit(0)).

**Comment by Baggykiin** [comment]
You're right, it seems like the handler for the Quit button calls `Close()` instead of `Exit()`, which only closes the main window. It's fixed now, if there are no further bugs this week I'll make a release for it.
