### ISSUE TITLE
Improve startup times?

### ISSUE THREAD

**Issue by alexzeitgeist** [Baggykiin/pass-winmenu#39]
Triggering pass-winmenu with the key shortcut feels kinda slow. I have around 1000 entries (.gpg files) stored on a ram disk, and it takes like two seconds to show the prompt. Using rafi on Linux feels instantaneously on a slower computer.

**Comment by Baggykiin** [comment]
Currently we enumerate the password directory when the user requests for a password to be decrypted. This isn't instantaneous, especially when you have a large number of files in the password store.

A better method would be to create an in-memory map of the location of all password files at startup, and then using a FileSystemWatcher to alter it when changes occur.

A lot of delay seems come from the inclusion of the `.git` directory in the search. I'll look into excluding that in the future, but for now, you could try running `git gc` in your password store to pack all the loose git objects, which can reduce the total number of files in your password store significantly.

**Comment by alexzeitgeist** [comment]
Hi Baggykiin, though I did delete the .git directory the delay is still quite noticable (~2 seconds). It is strange - as mentioned, the files are stored in ram, and for example a "dir /S" feels literally instantaneous. 

Not sure if it's the Directory.EnumerateFiles() method that's just slow or if it is something else in the code.

**Comment by Baggykiin** [comment]
You're right, looking through it a little more, it seems like building the menu itself is also a lot slower than it should be. I'm working on some improvements to the UI code, and I'd like to see if I'm on the right track.

Could you download a test build to see if it's any faster? You can get it from here:

https://ci.appveyor.com/api/buildjobs/nv0e856p11909uf7/artifacts/pass-winmenu%2Fbin%2FRelease%2Fpass-winmenu.exe

Just rename it, place it next to your current pass-winmenu executable, and run it. Hopefully it should be quite a bit faster. Can you tell me if that's the case?

**Comment by alexzeitgeist** [comment]
Hey, 

Speed is MUCH improved. Totally different experience. :) Well done.

**Comment by Baggykiin** [comment]
That's good to hear! Just keep in mind that the test version is still mostly untested. There are some more UI changes I'm working on, once those are done I'll publish a pre-release.

**Comment by Baggykiin** [comment]
Implemented as of v1.9
