### ISSUE TITLE
Donation link?

### ISSUE THREAD

**Issue by brandon-arnold** [Baggykiin/pass-winmenu#41]
Donation link would be nice. This is a slick passmenu clone.

**Comment by Baggykiin** [comment]
Thanks! I'll add a donation link, but it appears I'll need to set up a PayPal business account for that first.

**Comment by Baggykiin** [comment]
That turned out to be easier than I expected. I've added a donation link to the readme.

**Comment by brandon-arnold** [comment]
Nice. Works well

**Comment by Baggykiin** [comment]
Thank you very much! I can confirm that it works :)
