### ISSUE TITLE
Version without third party tools

### ISSUE THREAD

**Issue by majkinetor** [Baggykiin/pass-winmenu#9]
All 3thd party tools can be installed separately with a single command using chocolatey. If pass-winmenu is available on the chocolaty as well those tools will be installed automatically if they are mentioned as dependencies. 

cinst [gpg4win-vanilla](https://chocolatey.org/packages/gpg4win-vanilla/2.3.3) [7zip](https://chocolatey.org/packages/7zip) [git](https://chocolatey.org/packages/git)

This would allow one to use latest versions of such tools and reduce the size of the package itself which can be updated separately.

**Comment by Baggykiin** [comment]
The Git implementation relies on [LibGit2Sharp](https://github.com/libgit2/libgit2sharp) to work, which does have some native dependencies that need to be provided alongside the executable.

As far as GPG is concerned, it is definitely possible to release GPG-less builds, relying on a preinstalled GPG package instead. I'll look into doing this for the next release.

I do not have the experience to maintain a separate package on Chocolatey at this time, but if anyone wants to do this they're obviously free to do so. If you strip GPG from the release and edit the config file to point to the directory where Chocolatey installs GPG, it should work.

**Comment by majkinetor** [comment]
> The Git implementation relies on LibGit2Sharp to work

Sure. However, you need to have git to setup repository (if you use git as a sync method).

> I do not have the experience to maintain a separate package on Chocolatey at this time, but if anyone wants to do this they're obviously free to do so.

I will do that, and provide automatic package that will follow your releases with less then a day latency. You will have to provide tools free build. I guess 7z will also not be needed once the deps are on choco. I could put git as a dependency tho, as that is most likely to be used but I don't have to. This leaves us with 1 mandatory dep - gpg4win-vanilla. This will basically solve your issue #5.

I will make a package once the release is out.

**Comment by Baggykiin** [comment]
7zip is only a build dependency, used to create the zipfile releases which I push to GitHub, so that should indeed not be necessary for Chocolatey. Let me know if you run into any issues.

**Comment by Baggykiin** [comment]
CI will now build GPG-less versions as well. You can find these builds at https://ci.appveyor.com/project/baggykiin/pass-winmenu/build/artifacts

**Comment by majkinetor** [comment]
Great. Will you add it among Github releases ?

Looking at the zip could you clarify the purpose of

- lib\linux , lib\osx   
isn't this windows only project ? 
- lib\win32\\**\\*.pdb    
those add significantly to the archive and do not have any purpose for user

With those removed archive is down to ~2.4 MB (from 12). With only pdbs out its down to ~3.5MB.

**Comment by Baggykiin** [comment]
Yes, from release 1.6 onwards the GPG-less build will be available as a GitHub release.

The files you've mentioned are included since the build process generates them by default. I was already planning to remove those files from the builds for the reasons you specified, so I've made the necessary changes to the packaging script. The latest build should no longer include them.

**Comment by Baggykiin** [comment]
A GPG-less build is now available in the prerelease.

**Comment by majkinetor** [comment]
Great. I will now be able to finish choco package to use github releases as source for new versions.
